### ISSUE TITLE
Need to add tag for jitpack update

### ISSUE THREAD

**Issue by mortuzahossain** [tareq3/PushDown_ExtSingleClick#2]
Please add a tag at the latest commit #1 2.0.0 to make the update available in [jitpack](https://jitpack.io/)

@tareq3

**Comment by mortuzahossain** [comment]
@tareq3 brother, as we do major project structure change i think with symmetric versioning __2.0.0__ is the perfect choice. 

And i also changed the readme file with version number __2.0.0__

This is for your kind information ℹ️ 

If you think you stick with version __1.1__ then please change the version in readme

**Comment by tareq3** [comment]
release with tag 2.0  :D
